name: Storybook

on:
  push:
    branches: [ "master","dev" ]
  pull_request:
    branches: ["master","dev"]
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Build check
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm i
    - run: npm run build-storybook 
    - run: npm run storybook & npx wait-on http://localhost:6006
    - name: Accessbility check
      run: |
        npm install -g pa11y
        pa11y http://localhost:6006
    